### ISSUE TITLE
Weird output when parsing only spaces

### ISSUE THREAD

**Issue by ERPedersen** [Trott/node-slug#27]
Parsing only spaces creates a weird output.

See example below:

https://runkit.com/embed/8ho1mz0h48ph

**Comment by Trott** [comment]
It's generating a slug based on input that has not characters usable in the slug, so it's falling back to generating a predictable but necessarily-not-directly-related-to-the-input slug.

I'm comfortable with this behavior because weird-but-usable input is resulting in weird-but-usable output. But I'm open to other ideas. What output do you expect?

**Comment by ERPedersen** [comment]
I guess I was expecting just an empty string, however I do see your point being that the output is at least usable to some extent with the current implementation. I actually just stumbled upon it, and thought it was a bug.

In Laravel, the [Str class](https://laravel.com/api/5.5/Illuminate/Support/Str.html) provides a similar method, where the following rules apply among other:
- The output is trimmed before it is returned.
- Multiple consecutive spaces and/or separators are converted to single separators.

The output with a similar case would simply be an empty string. In my opinion that is a better solution, since it can be expected. I don't necessarily think that solves any problems better, but at least it delivers an output which can be expected.

**Comment by Trott** [comment]
I'm not sure an empty string is a useful slug, but that may just be a lack of imagination on my part. I expect that if I ask for a slug, I will get a non-empty string. The only case I *might* expect an empty string in return is if I supply an empty string as input. Is there a use case or some code that might show an empty string being a more ergonomic solution than a predictable-but-non-obvious slug (current behavior) or throwing an error? I'm contemplating adding an option that would throw on "OMG, can't slug this stuff" strings rather than "oh, well, let's generate a hash from the string rather than try to pull a meaningful slug out of it" which is the current behavior.

**Comment by Trott** [comment]
By the way, the big benefit to the current behavior is that it can make an ASCII slug from strings that contain *anything* like languages that use non-ASCII alphabets (e.g., Arabic, Japanese, etc.) or strings of emoji or whatever. And it can do it without the library needing to ship a big map of all those thousands and thousands of characters. To me, that's a pretty big upside. But there may be a case for treating all white space characters as un-sluggable?

**Comment by Trott** [comment]
> * The output is trimmed before it is returned.
> * Multiple consecutive spaces and/or separators are converted to single separators.

This library does that also. But if the resulting string is unsluggable, it falls back to this Base64 encoding-ish stuff you're seeing here.

**Comment by Trott** [comment]
I'm going to close this, but if you think there's a better way to handle this, please comment or re-open! Thanks!

**Comment by antonipelka** [comment]
Hey, first of all, really nice library, great job!

Wouldn't it be a better way to have base64 fallback as an option? Then it would be open for extension and if someone needed other encoding or no slug at all they could just add it on top of the library.

I would benefit from "no-slug" option in my project but I see that the underlying `slugify` function is encapsulated. If there was an easy way to access it then it would also be much nicer.

**Comment by Trott** [comment]
> I would benefit from "no-slug" option

That seems like a reasonable feature to add.

**Comment by antonipelka** [comment]
Just for some more context, because I was working with that today.
I needed to differentiate between slugs containing symbol only:
```ts
slug('&&') // generates [base64]
```
and some real language characters:
```ts
slug('üß') // generates "uss"
```

I don't want to allow the first case, therefore now I'm doing something like:
```ts
slug(`empty${input}`) !== 'empty' ? slug(input) : fallback
```

If we could do something like:
```ts
slug(input, { fallback: false }) || fallback
```
then it would be way easier to reason about it.

Thanks a lot!
